import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import TopNav from "./_components/TopNav";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "T3 Stack Gallery!",
  description: "Generated by a theo subscriber",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className={`flex flex-col gap-4 font-sans`}>
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
